import react from "react";
import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    containerThree: {
        width: 260,
        height: "auto",
        justifyContent: "center",
        backgroundColor: "lightblue",
        borderColor: "black",
        borderWidth: 2,
        borderRadius: 15,
        marginTop: 10,
    },
    teste2: {
        height: 150,
        width: 150,
        borderRadius: 100,
        marginTop: 2,
        marginBottom: 2,
    },
    container2: {
        right: 390,
    },
    container: {
        justifyContent: "center",
        alignItems: "center",
        marginTop:50
    },
    img: {
        marginTop: 10,
        width: 150,
        height: 150,
    },
    img2: {
        width: 50,
        height: 50,
    },
    img3: {
        width: 40,
        height: 40,
    },
    img4:{
        width: 50,
        height: 50,
        position: "absolute",
        left: 270,
        top: 10,

    },

    texto: {
        fontSize: 14,
        marginTop: 10,
        marginBottom: 5,
        color: "white",
        fontWeight: "bold",
    },
    input: {
        height: 45,
        borderWidth: 1,
        borderColor: "#222",
        backgroundColor: "white",
        fontSize: 20,
        padding: 10,
        borderRadius: 10,
        marginTop: 20,
    },
    btnTexto: {
        fontSize: 20,
        fontWeight: "bold",
        color: "#fff",
        textAlign: "center",
        textAlignVertical: "center",
        marginTop: 15,
    },
    botao: {
        marginTop: 20,
        height: 55,
        backgroundColor: "blue",
        borderWidth: 2,
        borderRadius: 10,
    },
    view: {
        width: 250,
        height: 400,
        borderRadius: 15,
        backgroundColor: "white",
        alignItems: "center",
        marginTop: 10,
    },
    view2: {
        height: 50,
        width: 240,
        borderRadius: 15,
        backgroundColor: "#dcedfa",
        marginTop: 5,
        borderColor: "#e9f1f4",
        borderWidth: 5,
    },
    view5: {
        height: 100,
        width: 240,
        borderRadius: 15,
        backgroundColor: "#dcedfa",
        marginTop: 5,
        borderColor: "#e9f1f4",
        borderWidth: 5,
    },

    view3: {
        height: 50,
        width: 240,
        borderRadius: 15,
        backgroundColor: "white",
        marginTop: 5,
        borderColor: "#07272d",
        borderWidth: 2,
        alignItems: "center",
        justifyContent: "center",
    },
    view4: {
        height: 600,
        width: 600,
        backgroundColor: "orange",
        marginTop: 25,
        borderRadius: 10,
        left: 150,
        justifyContent: "center",
        alignItems: "center",
    },
    textstyle: {
        fontSize: 15,
        color: "black",
    },

    textstyle1: {
        fontSize: 15,
        color: "white",
        height: 150,
    },
    logoutbtn: {
        bottom: 100,
        left: 500,
    },
    buttonText: {
        color: "white",
    },

    buttonProcurar: {
        height: 30,
        width: 240,
        backgroundColor: "#1dacd6",
        borderRadius: 10,
        borderWidth: 2,
        borderColor: "black",
        justifyContent: "center",
        alignItems: "center",
        top: 530,

        position: "absolute",
    },
    buttonTextProcurar: {
        color: "white",
        fontSize: 17,
    },
    btncotrato: {
        height: 50,
        width: 200,
        borderRadius: 5,
        borderColor: "red",
        backgroundColor: "pink",
        justifyContent: "center",
        alignItems: "center",
    },
    containerFive: {
        height: 500,
        width: 300,
        backgroundColor: "lightgreen",
        borderRadius: 10,
        position: "absolute",
        right: 100,
    },
    placa1: {
        height: 25,
        width: 260,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "gray",
        borderWidth: 2,
        borderRadius: 10,
        borderColor: "black",
        marginTop: 10,
        fontStyle: "italic",
    },
    pagConfigOne: {
        justifyContent: "center",
        alignItems: "center",
    },
    pagConfigTwo: {
        justifyContent: "center",
        alignItems: "center",
    },
    pagConfigTextStyle: {
        color: "white",
    },
    button: {
        height: 50,
        width: 200,
        backgroundColor: "lightyellow",
        borderRadius: 10,
        borderColor: "yellow",
        borderWidth: 2,
        alignItems: "center",
        justifyContent: "center",
        position: "absolute",
        top: 500,
    },
    buttonText: {
        color: "black",
    },
    btnContratoVisu1: {
        height: 50,
        width: 100,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "lightgreen",
        borderRadius: 10,
        borderColor: "green",
        borderWidth: 2,
        position: "absolute",
        right: 890,
        top: 540,
    },
    containerOnePagContrato: {
        justifyContent: "center",
        alignItems: "center",
    },
    containerTwoPagContrato: {
        alignItems: "center",
        justifyContent: "center",
        width: 270,
        height: 540,
        borderColor: "#1dacd6",
        borderWidth: 2,
        borderRadius: 10,
        marginTop: 20,
        backgroundColor: "white",
        marginTop:55
    },
    containerThreePagContrato: {
        width: 230,
        height: "auto",
        justifyContent: "center",
        backgroundColor: "#dcedfa",
        borderColor: "blue",
        borderWidth: 2,
        borderRadius: 10,
        marginTop: 10,
    },
    btnvoltarPagContrato: {
        height: 50,
        width: 100,
        borderRadius: 10,
        borderColor: "green",
        borderWidth: 2,
        backgroundColor: "lightgreen",
        justifyContent: "center",
        alignItems: "center",
        position: "absolute",
        top: 450,
    },
    containerOnePerfil: {
        justifyContent: "center",
        alignItems: "center",
        marginTop:60
    },
    containerTwoPerfil: {
        height: 555,
        width: 260,
        borderRadius: 10,
        borderWidth: 5,
        borderColor: "#001B79", 
        backgroundColor: "#93C6E7" ,
    },
    containerThreePerfil: {
        height: 535,
        width: 240,
        //borderWidth: 5,
        //borderColor: "#1dacd6",
        borderRadius: 10,
        marginTop: 5,
        marginHorizontal: 5,
        backgroundColor: "#93C6E7", //#1dacd6
        alignItems: "center",
    },
    imgPerfil: {
        height: 150,
        width: 150,
        borderRadius: 100,
        borderWidth: 10,
        borderColor: "gray",
        marginTop: 20,
    },
    textStylePerfil: {
        fontSize: 20,
        color: "white",
    },
    btnChatPerfil: {
        height: 50,
        width: 200,
        borderRadius: 10,
        borderColor: "black",
        borderWidth: 2,
        backgroundColor: "#AEE2FF", //#FEFFAC
        alignItems: "center",
        justifyContent: "center",
        marginTop: 10,
        top: 365,
        position: "absolute",
    },
    bntvoltarPerfil: {
        width: 150,
        height: 50,
        backgroundColor: "#45FFCA", //#FFB6D9 #FEDEFF
        borderColor: "black",
        borderRadius: 10,
        borderWidth: 2,
        justifyContent: "center",
        alignItems: "center",
        marginTop: 10,
        position: "absolute",
        top: 420,
    },
    btncontratarPerfil: {
        height: 25,
        width: 200,
        backgroundColor: "white", // #45FFCA
        borderWidth: 2,
        borderColor: "black",
        borderRadius: 15,
        marginTop: 8,
        justifyContent: "center",
        alignItems: "center",
        position: "absolute",
        top: 480,
    },
    viewPerfil: {
        height: 555,
        width: 600,
        backgroundColor: "orange",
        marginTop: 25,
        borderRadius: 10,
        left: 330,
        bottom: 5,
        justifyContent: "center",
        alignItems: "center",
        position: "absolute",
    },
    inputStyle: {
        height: 50,
        width: 230,
        backgroundColor: "#dcedfa",
        borderRadius: 10,
        borderColor: "black",
        borderWidth: 2,
        marginTop: 5,
    },
    inputStyle2: {
        height: 300,
        width: 230,
        backgroundColor: "#dcedfa",
        borderRadius: 10,
        borderColor: "black",
        borderWidth: 2,
        marginTop: 5,
        alignItems: "center",
        justifyContent: "center",
    },
    btnAceitar: {
        height: 50,
        width: 100,
        backgroundColor: "cyan",
        borderColor: "blue",
        borderWidth: 2,
        borderRadius: 10,
        justifyContent: "center",
        alignItems: "center",
        //position: "absolute",
        
        
    },
    btnNegar: {
        height: 50,
        width: 100,
        backgroundColor: "pink",
        borderColor: "red",
        borderWidth: 2,
        borderRadius: 10,
        justifyContent: "center",
        alignItems: "center",
        position: "absolute",
        left: 155,
    },
    inputStyle3: {
        height: 25,
        width: 260,
        backgroundColor: "grey",
        borderRadius: 10,
        borderColor: "black",
        borderWidth: 2,
        marginTop: 5,
        alignItems: "center",
        justifyContent: "center",
    },
    styleVisuContrato: {
        backgroundColor: "white",
        height: 550,
        width: 250,
        borderRadius: 10,
        marginTop: 10,
        alignItems: "center",
        justifyContent: "center",
        borderWidth:2,
        borderRadius:15, 
        borderColor:"#1dacd6"
    },
    container2: {
        justifyContent: "center",
        alignItems: "center",
    },
    bntvoltarPerfilContrato: {
        height: 25,
        width: 200,
        backgroundColor: "#1dacd6",
        borderRadius: 10,
        borderWidth: 2,
        borderColor: "black",
        justifyContent: "center",
        alignItems: "center",
        marginTop: 10,
    },
    btnCriarContrato: {
        height: 25,
        width: 200,
        backgroundColor: "lightyellow",
        borderWidth: 2,
        borderColor: "black",
        borderRadius: 10,
        marginTop: 10,
    },
    btnProcurarContrato: {
        marginTop: 5,
        height: 30,
        width: 240,
        borderRadius: 10,
        borderWidth: 2,
        borderColor: "black",
        backgroundColor: "lightblue",
        justifyContent: "center",
        alignItems: "center",
    },
    btnVoltarlistaContrato: {
        height: 25,
        width: 200,
        backgroundColor: "#1dacd6",
        borderColor: "white",
        borderWidth: 2,
        borderRadius: 15,
        justifyContent: "center",
        alignItems: "center",
        position: "absolute",
        top: 520,
    },
    loadingContaner:{
        alignItems:'center',
        justifyContent:'center',
        backgroundColor:'#dcedfa',
        flex:1
    }
});
export default styles;
